### ISSUE TITLE
Add a register now option on login screen for mobile view 

### ISSUE THREAD

**Issue by shyamTayal** [GeekHaven/WorkTrack#11]
Currently, on mobile screen view there is a hamburger menu which has an option of registering to the app which is not visible at once to user. Hence there should be an **option below the login screen to register and similarly below the register screen to login**

**Comment by sarthakm21** [comment]
Hey @shyamTayal great idea. Should I assign this to you?

**Comment by shyamTayal** [comment]
Yeah sure 👍
