### ISSUE TITLE
Add a Feature for User to visit his/her profile.

### ISSUE THREAD

**Issue by Elemento24** [GeekHaven/WorkTrack#17]
- In the navbar, there is a "Logged In As <username>" item. We can use it as a link for the user, to visit his/her profile. 
- So we can add some more options in the User Schema, like an option for an Image URL, social links, like twitter, facebook, linked in, etc
- We will ask for all these as an optional value, while registering, and accordingly render them on his profile.
- We will make a new route for a user to reach his/her profile!

I would like to work on this issue, can you please assign this to me.

**Comment by sarthakm21** [comment]
@Elemento24 assigned to you

**Comment by Elemento24** [comment]
![Screenshot from 2020-10-16 23-54-01](https://user-images.githubusercontent.com/58396433/96295236-2bc5cc80-100b-11eb-828a-ed881bae5295.png)
Hey @sarthakm21, this is a preview to the User Profile Route, and I have made sure to protect it with the isLoggedIn tomorrow
