### ISSUE TITLE
Change the Header text for a new user to make it more visible

### ISSUE THREAD

**Issue by sarthakm21** [GeekHaven/WorkTrack#18]
Currently, it looks like this.

![one](https://user-images.githubusercontent.com/58396189/95957230-11c69700-0e1d-11eb-91c3-7b18b602f233.PNG)

Its not very clearly visible. Change the top text's styles to increase its visibility. 
**Do not change anything that will affect other elements as well**

**Comment by sanskar-p** [comment]
Hey @sarthakm21, I'd like to work on this. What are your thoughts on just increasing the font weight? Or do you think it's a better idea to change the color to something darker?

**Comment by kumarmanish03** [comment]
Ok, I want to work on this

**Comment by sarthakm21** [comment]
@sanskar-p go ahead

**Comment by sarthakm21** [comment]
I'd prefer the color to be white. You can try anything otherwise. Try using shadow effects

**Comment by sanskar-p** [comment]
@sarthakm21, this is what the page looks like in https://work-track.herokuapp.com/home

![image](https://user-images.githubusercontent.com/54014518/95979442-45171f00-0e39-11eb-88ac-d0480869c350.png)

So am I viewing the wrong page or has this issue been resolved already?

**Comment by sarthakm21** [comment]
Oh no no no! Thats where the website is hosted and I have not updated it yet. You have to run the app locally on your system. Follow the steps in the repo's readme to run the app locally.

**Comment by sanskar-p** [comment]
@sarthakm21, how does this look to you? Would you prefer a blue/purple shadow instead?

![image](https://user-images.githubusercontent.com/54014518/95987994-dab8ab80-0e45-11eb-89ad-4897a5458772.png)

**Comment by sarthakm21** [comment]
Share the other ones as well so I can compare. Also, if you're changing font sizes, make sure that they are responsive and look good for all screen sizes :)

**Comment by sarthakm21** [comment]
@sanskar-p I also want the effects to be added to the "Get Started ......." text because that's also not very clear. Please add the styles to that as well. And in the above four, I like the 2nd one (its a bit more subtle)
