### ISSUE TITLE
Add Support for Sass and convert existing CSS into Sass

### ISSUE THREAD

**Issue by Elemento24** [GeekHaven/WorkTrack#28]
- In this, I would convert the existing CSS stylesheet into Sass.
- Also, I would use our NPM ecosystem to add support for Sass.
- We will be using BEM (Block Element Modifier) Methodology to name our classes. 

Hey @sarthakm21, I would like to work on this, can you please assign it to me!

**Comment by sarthakm21** [comment]
Go ahead!
