### ISSUE TITLE
Add a option on the home screen for the user to select the duration for which they want to see their works

### ISSUE THREAD

**Issue by sarthakm21** [GeekHaven/WorkTrack#3]
The user can select the time(in days) for which they wan't their works to be displayed. A dropdown menu would do the job!

**Comment by shahidsiddiqui786** [comment]
I want to work on this!
@sarthakm21 what exactly here we need to do?
![Screenshot_2020-10-12 Tryit Editor v3 6](https://user-images.githubusercontent.com/56132385/95715915-3e957580-0c88-11eb-896c-b14a93f4624f.png)
![Screenshot_2020-10-12 Tryit Editor v3 6(1)](https://user-images.githubusercontent.com/56132385/95715940-46551a00-0c88-11eb-86d4-bd4110f4b23a.png)

is it like that above?

**Comment by sarthakm21** [comment]
No not a search option, but a filter like system where the user can select the start date and end date from some menu and then we only display the works that were created between the selected time period

**Comment by shahidsiddiqui786** [comment]
okay ,I got it
assign me!

**Comment by sarthakm21** [comment]
Assigned 👍

**Comment by sarthakm21** [comment]
Hey, make sure that you link this issue to the PR that you'll make.
Add Fixes #<issue number> in the comments to link it to that issue

**Comment by sarthakm21** [comment]
Hey @shahidsiddiqui786, any updates?

**Comment by shahidsiddiqui786** [comment]
I 'm working on issue, 
but just confused how to get input data value in home.ejs file enter by user to re render the page
@sarthakm21 any guess! how to do it?
should I use  form to post data and then re render the page from show.js file?

**Comment by sarthakm21** [comment]
I think you'll need to create a new Post route to handle the form submissions.
