### ISSUE TITLE
Redesign of Profile Page

### ISSUE THREAD

**Issue by Elemento24** [GeekHaven/WorkTrack#30]
- A new feature has been added, in which a user can visit his/her profile.
- So, a design of Profile Page is needed.
- Feel free to change the semantic of userProfile.ejs file.
- **The work needs to be done in the profile branch,** so make sure that you fetch from it, and create a PR into that branch only.
- The current preview of the Profile Page is attached below!

![Screenshot from 2020-10-20 17-21-41](https://user-images.githubusercontent.com/58396433/96582609-26150300-12f9-11eb-8ad7-c4f1873c6485.png)

**Comment by IC1101Virgo** [comment]
Can I work on this?

**Comment by Elemento24** [comment]
Hey @IC1101Virgo , you can surely work on this! Just make sure to fetch from the Profile Branch, and when creating the PR, making it into the same Branch!

**Comment by sarthakm21** [comment]
@IC1101Virgo assigned it to you
