### ISSUE TITLE
Add a better background throughout the app

### ISSUE THREAD

**Issue by sarthakm21** [GeekHaven/WorkTrack#4]
It's plain white right now, and rather boring tbh. Select and add a new backgound that adds some life to the app. Nothing too flashy though. Something that matches with the overall theme of the app.

**Comment by rush-tea** [comment]
Hey @sarthakm21  Can i work on this ?

**Comment by CadencePrestissimo** [comment]
can I do this !

**Comment by sarthakm21** [comment]
Sure! Go Ahead

**Comment by geeks5551** [comment]
can i work on this @sarthakm21

**Comment by sarthakm21** [comment]
@geeks5551 Assigned this to you!

**Comment by sarthakm21** [comment]
@geeks5551 any updates?

**Comment by CadencePrestissimo** [comment]
Can I do this ?

**Comment by sarthakm21** [comment]
@CadencePrestissimo go ahead!

**Comment by sarthakm21** [comment]
@CadencePrestissimo since you already have submitted 6 prs during the Geektoberfest, I'm unassigning you from this issue.

**Comment by geeks5551** [comment]
Can i do this?

**Comment by sarthakm21** [comment]
Assigning it to you @geeks5551

**Comment by alkatrivedi** [comment]
I would like to work on it. May I?

**Comment by sarthakm21** [comment]
@alkatrivedi assigned it to you

**Comment by alkatrivedi** [comment]
On it. Thanks!

**Comment by alkatrivedi** [comment]
@sarthakm21 You want background image here only. Right?
![Capture](https://user-images.githubusercontent.com/58396306/96706857-c11ee300-13b4-11eb-9b11-4304fdf18bfd.JPG)

I did some changes please have a look.

**Comment by sarthakm21** [comment]
No actually I want a good background throughout the app. It's not necessary for it to be an image.

**Comment by alkatrivedi** [comment]
Can you please clarify what do you actually mean by throughout the app? I am slightly confused.

**Comment by alkatrivedi** [comment]
Did this means better background to the this whole "form page"? or something else. Please clarify.

**Comment by sarthakm21** [comment]
What I meant was, I want a background in all the sections. On the addWork section, home page, inspire me section etc. Though you can skip the your stats section. It doesnt really need a background

**Comment by alkatrivedi** [comment]
Alright! I got it, will do the changes today.

**Comment by namrata18s** [comment]
Can I work on this?

**Comment by alkatrivedi** [comment]
@sarthakm21 please review my PR #33
