### ISSUE TITLE
Add a timer to the AddWork section

### ISSUE THREAD

**Issue by sarthakm21** [GeekHaven/WorkTrack#5]
The timer would display the time elapsed since the user started the task. Looking for something along the lines of [this](https://codepen.io/henriquelothammer/pen/NWNQBwq) or maybe something more challenging like [this](https://codepen.io/bojari-zsolt/pen/XWdQXJW) (Not so flashy though)

**Comment by IC1101Virgo** [comment]
Can I work on this?

**Comment by sarthakm21** [comment]
Go Ahead :)
