### ISSUE TITLE
Give the user some notification when they try to visit a section without logging in

### ISSUE THREAD

**Issue by sarthakm21** [GeekHaven/WorkTrack#6]
It is not possible for the user to view the Home page, Add Work page and the Statistics page without logging in. Right now, when they try to do so, the app simply redirects to the login page. Some notification like **Please login first** would be much better.

**Comment by asingh1601** [comment]
I want to work on this

**Comment by sarthakm21** [comment]
Go Ahead :)

**Comment by thelavenderhue** [comment]
@sarthakm21 can I work on this?

**Comment by sarthakm21** [comment]
@thelavenderhue assigned it to you :)
