### ISSUE TITLE
Improve the Header in Inspire Me section

### ISSUE THREAD

**Issue by sarthakm21** [GeekHaven/WorkTrack#8]
Currently, it looks like this.

![Capture](https://user-images.githubusercontent.com/58396189/95672453-8b147e80-0bbe-11eb-94a3-c8a0a85bd8cd.PNG)

Its pretty basic. Change it so that it does not look so bland. Maybe add some image or icons(something relevant to the section of course) that makes it slightly more attractive!

**Comment by Mehul-12** [comment]
Interested, pl assign

**Comment by shahidsiddiqui786** [comment]
i want to work on it.

**Comment by sarthakm21** [comment]
Go Ahead :) 
And make sure that you do not modify the classes that other elements depend on! Create new ones if needed.
