### ISSUE TITLE
Add a show password icon on the login and signup form

### ISSUE THREAD

**Issue by sarthakm21** [GeekHaven/WorkTrack#9]
You can use this for reference [Show my password](https://codepen.io/AllThingsSmitty/pen/KgxmXv?editors=1010)

Font awesome is already included in the app so you can use the eye icon classes directly.

**Comment by cyucelen** [comment]
I can work on this issue

**Comment by sarthakm21** [comment]
Hey, @cyucelen thanks for your interest. However, for the time being this repo is part of an event being held exclusively for our organisation.

**Comment by cyucelen** [comment]
Alright, happy hacktober!

**Comment by ankit4284** [comment]
@sarthakm21 can i work on this issue?

**Comment by sarthakm21** [comment]
go ahead :)
